spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5445/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Порт, на котором будет запускаться сам веб-сервис заказов
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
